#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Filesystem\Filesystem;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else if (file_exists(__DIR__.'/../autoload.php')) {
    require __DIR__.'/../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

(new SingleCommandApplication())
    ->setName('PHP Check')
    ->setVersion('0.10.0')
    ->addOption('phpunit', 'p', InputOption::VALUE_OPTIONAL, 'run PHPUnit', false)
    ->addOption('list', 'l', InputOption::VALUE_OPTIONAL, 'list the files that are going to be fixed', false)
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $filesystem = new Filesystem();

        if (! $filesystem->exists('.php-cs-fixer.php')) {
            $output->writeln('⚙️ Installing .php-cs-fixer.php file. Run the script again to run php-cs-fixer.');
            $filesystem->copy(__DIR__ . '/config/laravel.stub', '.php-cs-fixer.php');
            exit(0);
        }

        if ($input->getOption('phpunit') !== false) {
            exec('./vendor/bin/phpunit', $commandOutput, $commandStatus);
            $output->writeln($commandStatus == 0 ? '✅ PHPUnit OK' : '❌ PHPUnit Not OK, run ./vendor/bin/phpunit to see more details.');
            exit(0);
        }

        if ($input->getOption('list') !== false) {
            exec('./vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.php --using-cache=false', $commandOutput, $commandStatus);
            $output->writeln($commandOutput);
            exit(0);
        }

        exec('./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --using-cache=false', $commandOutput, $commandStatus);
        $output->writeln($commandStatus == 0 ? '✅ php-cs-fixer OK' : '❌ php-cs-fixer Not OK, run php-cs-fixer fix --config=.php-cs-fixer.php to see more details.');
    })
    ->run();
